-- 005: 添加测试数据标记字段
ALTER TABLE students ADD COLUMN is_test TINYINT(1) DEFAULT 0;
ALTER TABLE teachers ADD COLUMN is_test TINYINT(1) DEFAULT 0;
ALTER TABLE courses ADD COLUMN is_test TINYINT(1) DEFAULT 0;
ALTER TABLE attendance ADD COLUMN is_test TINYINT(1) DEFAULT 0;
ALTER TABLE hour_records ADD COLUMN is_test TINYINT(1) DEFAULT 0;
ALTER TABLE course_handovers ADD COLUMN is_test TINYINT(1) DEFAULT 0;
