-- 将课时相关字段从 INT 改为 DECIMAL，支持 .5 小数
ALTER TABLE students MODIFY COLUMN total_hours DECIMAL(8,1) DEFAULT 0;
ALTER TABLE students MODIFY COLUMN used_hours DECIMAL(8,1) DEFAULT 0;
ALTER TABLE courses MODIFY COLUMN hours_per_class DECIMAL(4,1) DEFAULT 1;
ALTER TABLE attendance MODIFY COLUMN hours_deducted DECIMAL(4,1) DEFAULT 1;
ALTER TABLE hour_records MODIFY COLUMN hours DECIMAL(8,1) NOT NULL;
